apiVersion: v1
kind: Pod
metadata:
  name: webnginx
  labels:
    use: demo
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: '0.5'
          memory: 100Mi
        limits:
          cpu: '1'
          memory: 250Mi
      ports:
        - name: webaccess
          containerPort: 80
          protocol: TCP
