apiVersion: v1
kind: Pod
metadata:
  name: webnginx
  labels:
    use: demo
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
           - name: webaccess
             containerPort: 80
             protocol: TCP
